name: Data Pipeline

on:
  workflow_dispatch:
    inputs:
      raw_path:
        description: "s3://raw-bucket/path/"
        required: true
      clean_path:
        description: "s3://clean-bucket/path/"
        required: true

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Glue Job
        run: |
          aws glue start-job-run \
            --job-name liquor-sales-cleaning-job \
            --arguments "{
              \"--RAW_S3_PATH\": \"${{ github.event.inputs.raw_path }}\",
              \"--CLEAN_S3_PATH\": \"${{ github.event.inputs.clean_path }}\"
            }"
