name: Pipeline

on:
  workflow_dispatch:
    inputs:
      raw_s3_path:
        description: "RAW data S3 path"
        required: true
      clean_s3_path:
        description: "CLEAN data S3 path"
        required: true

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="raw_s3_path=${{ github.event.inputs.raw_s3_path }}" \
          -var="clean_s3_path=${{ github.event.inputs.clean_s3_path }}"
      working-directory: terraform

    - name: Run Glue Job & Wait
      run: |
        JOB_RUN_ID=$(aws glue start-job-run \
          --job-name liquor-sales-cleaning-job \
          --arguments "{\"--RAW_S3_PATH\":\"${{ github.event.inputs.raw_s3_path }}\",\"--CLEAN_S3_PATH\":\"${{ github.event.inputs.clean_s3_path }}\"}" \
          --query JobRunId --output text)

        echo "JobRunId: $JOB_RUN_ID"

        while true; do
          STATUS=$(aws glue get-job-run \
            --job-name liquor-sales-cleaning-job \
            --run-id $JOB_RUN_ID \
            --query JobRun.JobRunState \
            --output text)

          echo "Status: $STATUS"

          if [ "$STATUS" = "SUCCEEDED" ]; then break; fi
          if [ "$STATUS" = "FAILED" ]; then exit 1; fi

          sleep 30
        done

    - name: Run Glue Crawler
      run: aws glue start-crawler --name liquor-cleaned-crawler
