name: Full Data Pipeline

on:
  workflow_dispatch:
    inputs:
      raw_bucket:
        description: "RAW bucket name"
        required: true
      clean_bucket:
        description: "CLEAN bucket name"
        required: true
      script_bucket:
        description: "Glue script bucket"
        required: true

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="raw_bucket_name=${{ inputs.raw_bucket }}" \
          -var="clean_bucket_name=${{ inputs.clean_bucket }}" \
          -var="glue_script_bucket=${{ inputs.script_bucket }}"
      working-directory: terraform

    - name: Run Glue Job
      run: |
        aws glue start-job-run \
          --job-name liquor-sales-cleaning-job \
          --arguments \
            "--RAW_S3_PATH=s3://${{ inputs.raw_bucket }}/" \
            "--CLEAN_S3_PATH=s3://${{ inputs.clean_bucket }}/"
